### ISSUE TITLE
Online Markdown Preview

### ISSUE THREAD

**Issue by wewoor** [DTStack/molecule#535]
Refer to the Project https://github.com/DTStack/molecule-examples/tree/main/packages/online-code-formatting

**Comment by xu4wang** [comment]
sorry, cannot find 

https://github.com/DTStack/molecule-examples/tree/main/packages/online-code-formatting

it's 404 now.

**Comment by wewoor** [comment]
@xu4wang Sorry, the correct URL is: https://prettier.studio/
