### ISSUE TITLE
Error creating file

### ISSUE THREAD

**Issue by AndyZjy** [DTStack/molecule#551]
**Describe the bug**
在预览界面点击创建文件报错

**To Reproduce**

1. Go to ['...'](https://dtstack.github.io/molecule-examples/#/)
2. Click on 'New File'
3. See error

![image](https://user-images.githubusercontent.com/22025154/146294290-eb23b229-4bb9-493e-a972-fc59de6ba04a.png)

**Comment by wewoor** [comment]
@AndyZjy 这个问题移至 **molecule-examples** 中修复
