### ISSUE TITLE
项目初始加载有warning

### ISSUE THREAD

**Issue by qiepengfei** [DTStack/molecule#560]
**Describe the bug**
项目刚启动就有warning
Warning: Render methods should be a pure function of props and state; triggering nested component updates from render is not allowed. If necessary, trigger nested updates in componentDidUpdate.

Check the render method of ForwardRef.
    at http://localhost:3333/static/js/vendors~main.chunk.js:69321:5
    at div
    at MenuBar (http://localhost:3333/static/js/vendors~main.chunk.js:84158:5)
    at Connector (http://localhost:3333/static/js/vendors~main.chunk.js:78211:7)
    at div
    at div
    at div
    at div
    at WorkbenchView (http://localhost:3333/static/js/vendors~main.chunk.js:85848:5)
    at Connector (http://localhost:3333/static/js/vendors~main.chunk.js:78211:7)
    at MoleculeProvider (http://localhost:3333/static/js/vendors~main.chunk.js:78055:5)
    at App

**To Reproduce**
import React from 'react';
import { MoleculeProvider, Workbench } from '@dtinsight/molecule';
import '@dtinsight/molecule/esm/style/mo.css';
import extensions from './extensions';

function App() {
    return (
        <MoleculeProvider extensions={[]}>
            <Workbench />
        </MoleculeProvider>
    );
}

export default App;

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by wewoor** [comment]
@qiepengfei 应该是依赖的库还是老的 React API 用法，我们尽快升级

**Comment by wewoor** [comment]
@qiepengfei 暂时不影响功能正常使用

**Comment by qiepengfei** [comment]
> @qiepengfei 暂时不影响功能正常使用

好的，谢啦
