### ISSUE TITLE
@SQLGate Maybe we need to extract the locales into an isolated package in the future.

### ISSUE THREAD

**Issue by wewoor** [DTStack/molecule#565]
@SQLGate Maybe we need to extract the locales into an isolated package in the future.

_Originally posted by @wewoor in https://github.com/DTStack/molecule/issues/558#issuecomment-1000002106_

**Comment by SQLGate** [comment]
> 

I think so. It would be more effective if you could do something like the link below.
https://github.com/microsoft/vscode-loc

**Comment by SQLGate** [comment]
Please close issue @wewoor
