### ISSUE TITLE
使用中遇到的一些问题汇总

### ISSUE THREAD

**Issue by qiepengfei** [DTStack/molecule#579]
### Question
1、初始加载遇到一个报错（molecule版本：0.9.0-beta.1.1）
    Molecule can't add the action, because there is no headerToolBar in Explorer 
![image](https://user-images.githubusercontent.com/40254875/147623776-8d726cf1-1168-4dc3-8f9f-218a9f6ec253.png)

2、卸载组件后重新挂载出现了如下图的情况：
![image](https://user-images.githubusercontent.com/40254875/147623724-1f6513be-74e3-4b5a-b13e-9ef1104be2d0.png)

**Comment by wewoor** [comment]
@qiepengfei 感谢你的反馈

**Comment by wewoor** [comment]
@qiepengfei 你的第一个问题能不能提供更多的使用细节，或者你的意图

**Comment by wewoor** [comment]
@qiepengfei  有任何问题，欢迎在线交流：https://discord.gg/b62gpHwNA7

**Comment by qiepengfei** [comment]
> @qiepengfei 有任何问题，欢迎在线交流：https://discord.gg/b62gpHwNA7

稍等 我的邮箱验证有点问题 在里面不能发言

**Comment by qiepengfei** [comment]
> @qiepengfei 有任何问题，欢迎在线交流：https://discord.gg/b62gpHwNA7

不好意思啊 这个一直没上去 15101625301 你看你方便微信联系下吗？

**Comment by wewoor** [comment]
@qiepengfei 重复加载的问题，已经在 #580 中 fix了
