### ISSUE TITLE
Can I contribute to molecule without  Storybook?

### ISSUE THREAD

**Issue by guymoon** [DTStack/molecule#585]
## Question

Hello, thank you for making your repo public. It's such a fun repo.

I am trying to solve the issues of the Workbench component. But there's a problem. Storybook(`yarn dev`) mode and web(`yarn web`) mode are different.

![Screen Shot 2021-12-31 at 12 20 28 AM](https://user-images.githubusercontent.com/44131043/147764629-cfc32d52-93f2-4fc8-aa84-0d26ba6d6a56.jpg)

I can create files in Storybook like above. But it's impossible on the web. I can't click button(add folder)..  **How can I execute the mode like (next dev or react-scripts start)? Or Can you tell me how to develop it without Storybook?**

I'm not good at bundler and storybook. I'm so sorry ㅜㅜ I will definitely learn these things.

Thank you.
Happy New Year!!!!!!!

**Comment by wewoor** [comment]
@guymoon Actually,  `yarn dev` is our **development** env,  Storybook helps us to preview the component, and manage these components.  `yarn web` command is used to preview the molecule built source. 

Thanks for your feedback, we need to keep improving the Contributing docs. This is the Molecule Discord channel, if you have any questions can chat with us: https://discord.com/invite/b62gpHwNA7

**Comment by guymoon** [comment]
@wewoor Thanks you! I joined this discord channel!
