### ISSUE TITLE
bug: If there are many tabs, the scrollbar will appear large

### ISSUE THREAD

**Issue by SQLGate** [DTStack/molecule#588]
### Describe the bug

If there are many tabs, the scrollbar will appear large.

### Versions
-   OS: Window 10
-   Browser: Chrome, Edge

### To reproduce

Add as many editors as possible to create as many tabs as possible.

### Expected

Scrollbars should not be visible like in VSCode.
![image](https://user-images.githubusercontent.com/1125034/147876601-1ecdf8e9-070c-4c4b-8976-ea7524ef5dc8.png)

### Actually happening

![image](https://user-images.githubusercontent.com/1125034/147876577-61a0d3f1-b2e8-478f-b5ac-85f1abf6c2b9.png)

**Comment by guymoon** [comment]
this issue occurs when it is reduced below a certain range of editors. So it also occurs when the browser size becomes smaller.
