### ISSUE TITLE
bug: Moving tab into new tab group causes crash

### ISSUE THREAD

**Issue by hepezu** [DTStack/molecule#620]
### Describe the bug

Molecule crashes when tab is moved into other tab group.

### Versions

-   OS: Windows
-   Browser: Chrome
-   Molecule: @dtinsight/0.9.0-beta.1.1

### To reproduce

1. Use [official demo](https://dtstack.github.io/molecule-examples/#/) for demostration, open two editor tabs.
2. Split tab into two tab groups with button 'Split Editor Right' on the tab header.
3. Move one tab in a group to other group.

### Expected

Tab should be merged into new tab group.

### Actually happening

The app crashes with following error:

```
index.js:41 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at index.js:41:61
    at Array.map (<anonymous>)
    at Tabs (index.js:40:72)
    at renderWithHooks (react-dom.development.js:14985:18)
    at updateFunctionComponent (react-dom.development.js:17356:20)
    at beginWork (react-dom.development.js:19063:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at beginWork$1 (react-dom.development.js:23964:7)
```

**Comment by wewoor** [comment]
@hepezu Thanks for you feedback~

**Comment by wewoor** [comment]
> 

We have released the latest version, the demo does not upgrade yet. Maybe you can upgrade it manually.

**Comment by hepezu** [comment]
Thanks for your reply. The issue exists in the latest version. I noticed that it might not be an available feature(tab drag and drop between groups) at this moment, so I decide to close the issue.

In src/components/tabs/index.tsx, line 62
```js
    const onChangeTab = useCallback(
        (dragIndex, hoverIndex) => {
            const dragTab = data[dragIndex];
            onMoveTab?.(
                update(data, {
                    $splice: [
                        [dragIndex, 1],
                        [hoverIndex, 0, dragTab],
                    ],
                })
            );
        },
        [data]
    );
```

The target `Tabs` component(a tab group) consume the drag and drop event with `onChangeTab`. It gets the changed tab data with `const dragTab = data[dragIndex]`.

The current group can only visit its own tabs data, so if a tab from another group is dropped into the current group, the `dragTab` is undefined, and will cause errors in rendering. `if(dragTab)` can be added before updating state to solve this issue. The feature can be added in the future by exposing more data to tabs, but I think this feature is not very necessary.
