### ISSUE TITLE
bug: Editor tab group cannot restore to correct size after changing size, closing and reopening split group

### ISSUE THREAD

**Issue by hepezu** [DTStack/molecule#644]
### Describe the bug

Editor tab group cannot restore to correct size after changing size, closing and reopening split group.

### Versions

-   OS: Windows
-   Browser: Chrome
-   Molecule: 0.9.0-beta.3

### To reproduce

1. Open split tab group.
2. ** Change size of split group.**
3. Close the splited group.
4. Reopen split tab group.

### Expected

Restore to saved size.

### Actually happening

The size is incorrect.

### Related code

[Code in Editor.tsx](https://github.com/DTStack/molecule/blob/ec0d4591ac8b3209571446a94e35eab67fbfc7ca/src/workbench/editor/editor.tsx#L61)

```
initialSize={
    groupSplitPos[index]
        ? `${groupSplitPos[index]}ratio`
        : undefined
}
```

The `ratio` causes incorrect size to split pane. Remove `ratio`  to fix.

**Comment by hepezu** [comment]
I also have a suggestion on custom editor tab [group.tsx](https://github.com/DTStack/molecule/blob/ec0d4591ac8b3209571446a94e35eab67fbfc7ca/src/workbench/editor/group.tsx#L117). Exposing more props to renderPane would be great for customizing, for example `tab.renderPane({...tab.data, tabId: tab?.id, groupId: id})`.

**Comment by mortalYoung** [comment]
> I also have a suggestion on custom editor tab [group.tsx](https://github.com/DTStack/molecule/blob/ec0d4591ac8b3209571446a94e35eab67fbfc7ca/src/workbench/editor/group.tsx#L117). Exposing more props to renderPane would be great for customizing, for example `tab.renderPane({...tab.data, tabId: tab?.id, groupId: id})`.

How about give us a PR about this improvement :)
