### ISSUE TITLE
feat:Exposing more props to renderPane for EditorTab

### ISSUE THREAD

**Issue by wewoor** [DTStack/molecule#649]
I also have a suggestion on custom editor tab [group.tsx](https://github.com/DTStack/molecule/blob/ec0d4591ac8b3209571446a94e35eab67fbfc7ca/src/workbench/editor/group.tsx#L117). Exposing more props to renderPane would be great for customizing, for example `tab.renderPane({...tab.data, tabId: tab?.id, groupId: id})`.

_Originally posted by @hepezu in https://github.com/DTStack/molecule/issues/644#issuecomment-1024910401_

**Comment by mumiao** [comment]
这个问题比较好解 跟景明对齐 他来解决。我这周杂事比较多
