### ISSUE TITLE
bug:  After changing the folder name on the foldertree component, the sub file or the directory of the sub folder cannot be found 

### ISSUE THREAD

**Issue by Rao-Zhi** [DTStack/molecule#662]
### Describe the bug

After changing the folder name on the foldertree component, the sub file or the directory of the sub folder cannot be found

### Versions
OS: macos
Browser: electron
Molecule: 0.9.0-beta.3.1

### To reproduce
When the rename function on the right-click folder modifies the name successfully, click the sub file or folder, and then an error will be reported to prompt the directory error

### Expected

After I change the folder name, the sub files and the directory of the sub folder should be modified synchronously to prevent the directory from missing,Modify mole folderTree. Onupdatefilename (file) parameter, because the name field has been replaced, but the hierarchical route of the path file has not been replaced

### Actually happening
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/70873607/154957106-6a910124-b077-4522-9d69-d7cdaadeb6eb.png">
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/70873607/154957490-81ea95da-471d-4b07-a2f0-bceccbebdf09.png">

**Comment by mortalYoung** [comment]
You find the sub folders or the sub files by path? We don't recommend to do like that. It's more like each treeNode should has an unique and constant id like uid or pid in linux, and when you want to open this file or get the sub files of this folder, you should pass through this id to server which response for finding the sub files of this id.

**Comment by Rao-Zhi** [comment]
> 您通过路径找到子文件夹或子文件？我们不建议这样做。更像是每个treeNode都应该有一个唯一且恒定的id，如linux中的uid或pid，当你想打开这个文件或获取这个文件夹的子文件时，你应该通过这个id传递给服务器，找到子的响应此 id 的文件。

I operate node JS to change the local directory, maybe you didn't do this step, maybe it's my problem

**Comment by mortalYoung** [comment]
here is a way I can share to you:
1. press `ls -i` in your iterm, you'll get the inode number of each file in current folder.
2. and then you can use it as id
3. when you want to get the content of this file, you can run command line `find ./ -inum xxxxxx | xargs cat`.

this is what I practiced before

https://github.com/mortalYoung/cloudide-server/blob/15da544a2529d5f38455598f72883f37f7ac92f0/routes/mo.js#L139-L150

**Comment by Rao-Zhi** [comment]
In this way, you can directly read and change the contents without paying attention to the local path and directly transmitting the local number. Is this understanding right

**Comment by mortalYoung** [comment]
> In this way, you can directly read and change the contents without paying attention to the local path and directly transmitting the local number. Is this understanding right

yes, that's right
