### ISSUE TITLE
Notifications not popping up

### ISSUE THREAD

**Issue by oliexe** [DTStack/molecule#717]
### Question

Unread notifications are only marked by a dot in the notification icon. Is there any way to make them pop up as soon they are added? It's a bit useless in a lot of situations when the user is not notified right away by a visible notification.

Thanks.

**Comment by wewoor** [comment]
@oliexe Thanks for your feedback. Are you tried the [`molecule.notification.toggleNotification()`](https://dtstack.github.io/molecule/docs/next/api/interfaces/molecule.INotificationService#togglenotification) API?  You can refer to https://dtstack.github.io/molecule/docs/next/api/interfaces/molecule.INotificationService.

**Comment by oliexe** [comment]
Thanks, that solved it !
