### ISSUE TITLE
yarn web error

### ISSUE THREAD

**Issue by xinglongjian** [DTStack/molecule#718]
### Question

![image](https://user-images.githubusercontent.com/7200084/161419577-ec0c8f64-60db-43a1-9379-6fbf1712a46f.png)

**Comment by xinglongjian** [comment]
当执行yarn web的时候报错，这个有解决办法吗

**Comment by mortalYoung** [comment]
是在 main 分支是吗

**Comment by xinglongjian** [comment]
main分支也是这样
