### ISSUE TITLE
Disabling problems 

### ISSUE THREAD

**Issue by oliexe** [DTStack/molecule#720]
Hello,

Is there any way I can disable the "Problems" tab globally as it is not needed n our particular use case?

**Comment by mortalYoung** [comment]
Of course, you can try to remove the problem panel in statusBar
```js
molecule.statusBar.remove(molecule.builtin.getConstant('STATUS_PROBLEMS')!.value);
```

**Comment by mortalYoung** [comment]
And the "Problems" tab in panels could remove by 
```js
```
