### ISSUE TITLE
bug: there is an unseen string

### ISSUE THREAD

**Issue by mortalYoung** [DTStack/molecule#721]
there is an unseen string after the `↩`
https://github.com/DTStack/molecule/blob/05ad264912b169d86ff503c243940821bb5d7273/src/model/keybinding.ts#L7

### Expected

```js
'↩︎'.split('') // ['↩']
```

### What happened in actually
```js
'↩︎'.split('') // ['↩','']
```

**Comment by Zaoei** [comment]
```
'↩︎'.split('') // ['↩', '︎'] \u21a9\ufe0e
'↩'.split('') // ['↩'] \u21a9
```
