### ISSUE TITLE
bug: 无法正常启动molecule

### ISSUE THREAD

**Issue by arteuryu** [DTStack/molecule#728]
### Describe the bug

使用npm run start后，chrome浏览器报Uncaught TypeError: Cannot read properties of undefined 、

### Versions

-   OS:centos7.7
-   Browser:chrome
-   Molecule:latest

### Expected

正常显示

### Actually happening

![image](https://user-images.githubusercontent.com/2578223/165272706-8ae63894-097f-40b1-af47-32605a361ee9.png)

**Comment by wewoor** [comment]
clone Molecule 到本地吗？我们推进你使用 yarn 来安装，保持依赖版本一致

**Comment by mortalYoung** [comment]
可以提供一下项目里的 react 版本吗，如果是 raect@18 的话，目前是还没有兼容
