### ISSUE TITLE
bug: Close All Tabs won't clear the problems' count

### ISSUE THREAD

**Issue by mortalYoung** [DTStack/molecule#730]
### Versions

-   OS: MacOS 
-   Browser: FireFox
-   Molecule: @dtinsight/molecule 0.9.0-beta.4.2

### To reproduce
- Open a tab with problem
- Open another tab without problem
- close all tabs by content menu

### Expected
- the status of problem will be clear

### Actually happening
- the status of problem still in

![2022-04-27 15-37-37 2022-04-27 15_38_52](https://user-images.githubusercontent.com/18719701/165466863-0045b533-330b-42ab-be8e-7397c9687b80.gif)

**Comment by BojunZhong** [comment]
你做成这样的源码有吗，可以拿来学习下吗

**Comment by mortalYoung** [comment]
That's not molecule's problem. It's my fault.
