### ISSUE TITLE
bug: can't prevent default behavior about close tab

### ISSUE THREAD

**Issue by mortalYoung** [DTStack/molecule#737]
### Describe the bug
refer to: https://github.com/DTStack/Taier/issues/459

I need a confirm before close, but no matter `editor.onClose` or something else, it all can't prevent close.

### Versions

-   OS: MacOS
-   Browser: chrome
-   Molecule: 0.9.0-beta.4.2

### Expected

I can have a confirm to prevent close by some way.

**Comment by mumiao** [comment]
1. VIew层触发了`closeTab`方法，会执行 `EditorController`的`onCloseTab`，这里面主要是调用`editorService`的`closeTab`关闭tab以及`emit`一个closeTab的行为供用户监听

2. 用户想在`closeTab`之前增加二次弹窗，可以自定义`EditorController`的`onCloseTab`行为
```typescript
  modal.show();  // 自定义逻辑
  this.editorService.closeTab(tabId, groupId);
  this.emit(EditorEvent.OnCloseTab, tabId, groupId);
```

目前内置的**extensions**主要是考虑**Molecule Web**主界面的UI交互，**Editor**部分大部分的**actions**都会遇到增加二次确认的场景，因此用户有特殊需求。可以定制**controller**行为即可, 或者采用自己的**controller**

关于closeTab 内置行为主要是closeTab。其他的都交给用户了，把这部分从extensions剔除掉也不合适


@mortalYoung

**Comment by mortalYoung** [comment]
评估了一下有破坏性变更，放到下个 minor 版本做
