### ISSUE TITLE
C语言的语法插件在哪

### ISSUE THREAD

**Issue by BojunZhong** [DTStack/molecule#749]
### Question

C语言的语法插件，包括C语言的代码自动补全，语法高亮以及代码折叠，我想实现这个，到底在哪个包下？是在这个包被调用嘛@dtinsight/molecule/esm，具体而言呢？

**Comment by wewoor** [comment]
@BojunZhong C 语言之间使用 monaco-editor 内置的language 就可以了，具体参考：
https://github.com/microsoft/monaco-editor/tree/main/src/basic-languages，

使用可以参考：
https://dtstack.github.io/molecule/docs/next/quick-start#use-monaco-editor-language-pack
