### ISSUE TITLE
关于快捷键进函数或变量跳转的问题

### ISSUE THREAD

**Issue by BojunZhong** [DTStack/molecule#755]
### Question

ctrl + 鼠标 放在函数或变量等参数上可以跳转
这个功能在visual studio都能实现，这个功能在 molecule上如何实现，在快速开始有很多章节，其中就包括快捷键的设置，但是如何实现鼠标按在特定函数以及参数这个功能啊？

**Comment by BojunZhong** [comment]
https://github.com/microsoft/monaco-editor/blob/ab869e8469cd1cda70d25bb454732f84b523098c/src/language/typescript/languageFeatures.ts#L1068
这个网站我看了下，搜索了ctrl 找不到，

**Comment by wewoor** [comment]
这个应该是基于 `monaco-editor` 实现，我贴的是 language Code Action 的例子
