### ISSUE TITLE
bug: Can't change welcome page in editor in latest version

### ISSUE THREAD

**Issue by oliexe** [DTStack/molecule#760]
```
/**
     * The welcome page of editor bench
     */
    entry?: React.ReactNode;
```

Specifying entry in EditorView does not change the welcome screen in  **0.9.0-beta.4.2**.
This was functional in previous versions.

**Comment by mortalYoung** [comment]
Hi. Would you mind upgrade to v1.0.2 and check whether this problem still exist.

**Comment by oliexe** [comment]
@mortalYoung 
This is still not functional in 1.0.2

**Comment by mortalYoung** [comment]
To be honest, I couldn't find the reason why this was still not functional in 1.0.2 until I realized the difference between `React.ReactNode` and `JSX.Element`. 

I guessed the reason must be incorrect usage.

It should be used like:
```js
molecule.editor.setEntry(<YourComponent />)
```
