### ISSUE TITLE
这个有没有汇编语言导入

### ISSUE THREAD

**Issue by BojunZhong** [DTStack/molecule#761]
### Question

我想添加语言高亮的语法包------汇编语言，那怎么办啊，在Monaco editor里面有哪个包是汇编语言的

**Comment by mortalYoung** [comment]
貌似 monaco editor 自带的语言高亮不包括汇编，refer to:https://github.com/microsoft/monaco-editor/tree/main/src/basic-languages

**Comment by BojunZhong** [comment]
有什么别的办法吗？难道一定要像Taier一样自己去一个个敲上去？

**Comment by BojunZhong** [comment]
自己去定义语法规则，等等等，然后再把语法包导入进去？

**Comment by wewoor** [comment]
@BojunZhong 你可以在 Github 上搜索一下，应该有人已经写过针对 汇编语言 monaco-editor 的语言包
