### ISSUE TITLE
bug: Can't expand the FolderTree programatically

### ISSUE THREAD

**Issue by oliexe** [DTStack/molecule#764]
When trying to expand the folderTree nodes like described:

`molecule.folderTree.setExpandKeys([0, 2])
`

Nothing happens. Is there any workaround?

**Comment by wewoor** [comment]
> When trying to expand the folderTree nodes like described:
> 
> `molecule.folderTree.setExpandKeys([0, 2]) `
> 
> Nothing happens. Is there any workaround?

Hey @oliexe , good question! This feature is not supported before release. We plan to release a new version soon, it includes that, refers to https://dtstack.github.io/molecule/docs/next/api/classes/molecule.FolderTreeService/#setexpandkeys

**Comment by mortalYoung** [comment]
We released v1.0.2 in which fixed it last week.

**Comment by oliexe** [comment]
@mortalYoung 

Can you please explain how to use it ?

In 1.0.2 when i call  molecule.folderTree.setExpandKeys([3]) nothing happens, the tree with that ID does not get expanded...

**Comment by oliexe** [comment]
@mortalYoung 

Root folder (With id 0) is not possible to be expanded with this function - that is making it quite useless.
