### ISSUE TITLE
bug: Version 1.0.0 renders all panels twice.

### ISSUE THREAD

**Issue by oliexe** [DTStack/molecule#767]
### Description

Upgrading to Molecule UI 1.0.0 now causes the app elements to be rendered twice on app startup - this makes the app unusable because these elements have the same id and that causes multiple errors during any app interaction.

![sample2](https://user-images.githubusercontent.com/441290/174555043-cf5ff59d-2acd-480c-97be-cbc1d58c7405.png)
![sample1](https://user-images.githubusercontent.com/441290/174555044-7211c83f-16b7-4c18-9e59-0b4052b49970.png)

**Comment by mortalYoung** [comment]
Sorry, I can't reproduce this bug, Would you mind provide more informations about this bug? Do you call `render` function twice?
