### ISSUE TITLE
Molecule 中的 Monaco Editor  抽象一层，以插件的形式实现

### ISSUE THREAD

**Issue by wheatma38** [DTStack/molecule#792]
如题：
     Monaco Editor Command Palette 和框架绑定太紧密了，建议抽象出一个Editor 服务或接口以插件的形式提供功能。

需求：
     1. 可以扩展使用其他的editor 框架 
     2. 中间区域可以个性化不同的功能，比如类似 jupyter 的编辑器，数据分析图形展示等。

期待你的回复，  ：）

**Comment by mortalYoung** [comment]
针对你说的需求有如下解释：
1. 中间区域是可以个性化不同的功能，包括 jupyter 的编辑器，或者 code-mirror 都可以，我们在 [Taier](https://github.com/DTStack/Taier) 中基于 mxGraph 实现了工作流的编辑器

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/18719701/187012624-9cb53273-324c-4731-af67-526b8cdde6cd.png">

2. 但是目前来说 Command Palette 还无法自定义，目前暂时没有考虑到用户存在需要自定义 Command Palette 的需求，如果有可能可以说一下你们项目里自定义 Command Palette 的必要性吗

**Comment by wheatma38** [comment]
谢谢你的回复！     
     molecule 是一款设计优雅的框架，接口和服务定义清晰，（小巧不复杂）如果在框架基础上形成定制或个性化的扩展就可能形成自己的特点或生命长周期，针对中小团队友好的扩展。与同类产品形成差异化，如 Visual Studio Online ，Eclipse Theia （这些产品太重了）。

   针对我们项目需求来说，即在中间edit 编辑区域不是针对各种编程语言进行代码编写，有点像jupyter 写定制python/sql  语句，返回data table 或 echars 等进行数据分析。  如 sqlA --> ResultA ---> sqlB（获取ResultA结果集的内容）--ResultB ，所以有了上述提议。

**Comment by mortalYoung** [comment]
你说的这个需求我个人理解应该不需要自定义 Command Palette，只需要封装好你的组件，然后穿给 editor 就可以了。
```js
molecule.editor.open({
    // 一些 tab 的属性
    renderPane: () => <YourComponent />
})
```

**Comment by wheatma38** [comment]
谢谢，正在熟悉中....
