### ISSUE TITLE
内置的monaco-editor的右键菜单如何汉化

### ISSUE THREAD

**Issue by BySlin** [DTStack/molecule#796]
### Question

![image](https://user-images.githubusercontent.com/16970823/187668032-1008b943-4a31-455e-9a84-f30b144a2fc4.png)

如图

**Comment by mortalYoung** [comment]
这个汉化有点问题，应该下个版本想办法修复

**Comment by BySlin** [comment]
> 我们调研一下解决方案，不确定这个好不好解决，因为我发现 monaco-editor 上 [microsoft/monaco-editor#784](https://github.com/microsoft/monaco-editor/issues/784) 这个挂了好几年没解决了

可以试试使用 @monaco-editor/react 来加载编辑器，
```typescript
import { loader } from "@monaco-editor/react";

// you can configure the locales
loader.config({ "vs/nls": { availableLanguages: { "*": "zh-cn" } } });
```

**Comment by threefish** [comment]
此问题我已通过打包重写源码解决。
[链接地址](https://github.com/threefish/vite-plugin-monaco-editor-nls)

**Comment by wewoor** [comment]
> 此问题通过打包重写源码可以解决 [链接地址](https://github.com/threefish/vite-plugin-monaco-editor-nls)

@BySlin 可以参考下这个朋友的方案
