### ISSUE TITLE
bug: 给EditorTab配置icon不生效

### ISSUE THREAD

**Issue by BySlin** [DTStack/molecule#804]
### Describe the bug
给EditorTab配置icon不生效

![image](https://user-images.githubusercontent.com/16970823/190616127-4261dc09-13ed-4a8a-a14d-6a7c7aa8d3ed.png)

### Versions

-   OS:
-   Browser:
-   Molecule:

**Comment by wewoor** [comment]
@BySlin 使用 Icon 的方式是怎样的呢？是内置的图标吗？

**Comment by BySlin** [comment]
> @BySlin 使用 Icon 的方式是怎样的呢？是内置的图标吗？

传了一个标签过去了，内置图标是生效的，传标签在左侧目录树是生效的
```
{ icon: <span style={{ color: '#0cbb52' }}>GET</span> }
```

**Comment by wewoor** [comment]
> > @BySlin 使用 Icon 的方式是怎样的呢？是内置的图标吗？
> 
> 传了一个标签过去了，内置图标是生效的，传标签在左侧目录树是生效的
> 
> ```
> { icon: <span style={{ color: '#0cbb52' }}>GET</span> }
> ```

这个使用应该是没问题的，在控制台 Debug 这里有正确渲染 span 元素吗？

**Comment by BySlin** [comment]
![image](https://user-images.githubusercontent.com/16970823/190901666-070050ac-9cc2-450f-be8d-c209e3914d8f.png)

找到问题了 因为 .mo-tab__item__label 的fontSize默认是0，设置下字体大小就出来了
