### ISSUE TITLE
如何获取monaco-editor实例？我实现了lsp服务，可以在monaco-editor中进行代码提示，但是不知道如何集成到molecule中

### ISSUE THREAD

**Issue by threefish** [DTStack/molecule#809]
### Question

请问如何获取monaco-editor实例？我实现了lsp服务，可以在monaco-editor中进行代码提示，但是不知道如何集成到molecule中.

**Comment by wewoor** [comment]
> ### Question
> 请问如何获取monaco-editor实例？我实现了lsp服务，可以在monaco-editor中进行代码提示，但是不知道如何集成到molecule中.

可以通过 `molecule.editor.editorInstance` 获取当前的 editor实例
