### ISSUE TITLE
bug: Problems 面板和 OutPut面板切换2-3次后无法切换，并且控制台报错

### ISSUE THREAD

**Issue by threefish** [DTStack/molecule#812]
### Describe the bug

Problems 面板和 OutPut面板切换2-3次后无法切换，并且控制台报错

### Versions

1.1.1

-   OS: WIN10
-   Browser: edge
-   Molecule: 1.1.1

### To reproduce

https://dtstack.github.io/molecule-examples/#/ 在线demo可以复现

### Expected

可以正常切换

### Actually happening

`
4.c1d4df69.chunk.js:2 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at 4.c1d4df69.chunk.js:2:274187
    at ci (4.c1d4df69.chunk.js:2:644537)
    at 4.c1d4df69.chunk.js:2:645805
    at jt (4.c1d4df69.chunk.js:2:635541)
    at ci (4.c1d4df69.chunk.js:2:645761)
    at 4.c1d4df69.chunk.js:2:645701
    at Map.forEach (<anonymous>)
    at ci (4.c1d4df69.chunk.js:2:645670)
    at 4.c1d4df69.chunk.js:2:645805
    at jt (4.c1d4df69.chunk.js:2:635541)
`

**Comment by mortalYoung** [comment]
看起来是拷贝的时候导致的问题
