### ISSUE TITLE
请问molecule有没有可能升级 monaco-editor 版本到最新版本0.34.1 ？

### ISSUE THREAD

**Issue by threefish** [DTStack/molecule#817]
### Question
请问[molecule](https://github.com/DTStack/molecule)有没有可能升级 monaco-editor 版本到最新版本0.34.1  ? 
我在做集成LSP功能，目前有2个成果。

第1个是monaco-editor在0.34.1上结合最新版本的  [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) 可以实现代码智能提示和自动完成。
第2个是monaco-editor在0.29.1及以下版本 使用 [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient)的低版本0.14.0可以实现代码智能提示。

我尝试升级 monaco-editor 版本但是molecule使用了monaco-editor一些api，而这些api在后续的版本中被移除了导致不兼容，丢失的api导致molecule无法编译或者代码提示功能失效。

我尝试修改molecule，monaco-languageclient 源码，但是遇到各种报错编译失败的问题。molecule和monaco-languageclient都是代码架构非常优秀的项目，由于我本人主力工作是后端，前端个人水平有限，导致该项工作无法进行推进下去，所以提出以上问题，能不能升级都没关系，感谢。

**Comment by wewoor** [comment]
> ### Question
> 请问[molecule](https://github.com/DTStack/molecule)有没有可能升级 monaco-editor 版本到最新版本0.34.1 ? 我在做集成LSP功能，目前有2个成果。
> 
> 第1个是monaco-editor在0.34.1上结合最新版本的 [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) 可以实现代码智能提示和自动完成。 第2个是monaco-editor在0.29.1及以下版本 使用 [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient)的低版本0.14.0可以实现代码智能提示。
> 
> 我尝试升级 monaco-editor 版本但是molecule使用了monaco-editor一些api，而这些api在后续的版本中被移除了导致不兼容，丢失的api导致molecule无法编译或者代码提示功能失效。
> 
> 我尝试修改molecule，monaco-languageclient 源码，但是遇到各种报错编译失败的问题。molecule和monaco-languageclient都是代码架构非常优秀的项目，由于我本人主力工作是后端，前端个人水平有限，导致该项工作无法进行推进下去，所以提出以上问题，能不能升级都没关系，感谢。

我们评估下，看尽快发一个版本支持下

**Comment by threefish** [comment]
我已经解决了版本兼容问题，可以集成LSP功能。以下为对应版本配置，我在此分享一下

`
    "@codingame/monaco-jsonrpc": "0.3.1",
    "@codingame/monaco-languageclient": "0.17.4",
    "@dtinsight/molecule": "1.2.0",
    "reconnecting-websocket": "4.4.0",
    "monaco-editor": "0.30.1"
`
