### ISSUE TITLE
bug: FolderTreeService的getExpandKeys和setExpandKeys方法不生效

### ISSUE THREAD

**Issue by StrangeXin** [DTStack/molecule#818]
### Describe the bug

FolderTreeService的getExpandKeys和setExpandKeys方法不生效，getExpandKeys返回的永远是空数组，setExpandKeys无效
使用场景：异步获取目录后，设置默认展开文件夹

### Versions

-   OS:
-   Browser:
-   Molecule:

**Comment by wewoor** [comment]
@StrangeXin 能不能提供下你更具体的使用示例呢？我们在 Taier 里有个例子的：

https://github.com/DTStack/Taier/blob/0e2b0305a821d2683987e7f100dadafd78c2fb02/taier-ui/src/extensions/folderTree/index.tsx#L138

**Comment by mortalYoung** [comment]
在目前 1.2.0 的版本里无法复现，可以提供一下版本和复现操作吗？

**Comment by StrangeXin** [comment]
molecule.folderTree没问题，FolderTreeService不行，可以在taier里看下ResourceManagerTree或者FunctionManagerService能不能getExpandKeys和setExpandKeys

**Comment by StrangeXin** [comment]
我这边的情况是：使用molecule自定义新增目录树，用molecule.folderTree不太灵活，只能参考像taier的资源管理和函数管理一样自己写，但是FolderTreeService提供的部分方法、属性和antd的tree组件还是有差别，希望这块能对齐一下

**Comment by wewoor** [comment]
> 我这边的情况是：使用molecule自定义新增目录树，用molecule.folderTree不太灵活，只能参考像taier的资源管理和函数管理一样自己写，但是FolderTreeService提供的部分方法、属性和antd的tree组件还是有差别，希望这块能对齐一下

如果是完全使用其他 UI 组件库的部分组件，这里可以尝试自己封装状态独立的 FolderTreeService，用其他方法管理组件状态也行， 其实工作量也还好的。

**Comment by mortalYoung** [comment]
> 我这边的情况是：使用molecule自定义新增目录树，用molecule.folderTree不太灵活，只能参考像taier的资源管理和函数管理一样自己写，但是FolderTreeService提供的部分方法、属性和antd的tree组件还是有差别，希望这块能对齐一下

目前 taier 里面的资源管理和函数管理里面没有把 expandKeys 挂到 services 上，而是放在 state 里的，具体可以看下 https://github1s.com/DTStack/Taier/blob/HEAD/taier-ui/src/pages/resource/index.tsx#L384-L385。`FolderTreeView` 这个组件是一个纯粹的 UI 组件，需要外部值的传入， 这个外部值可以来自于 service 也可以来自父组件的 state，molecule.folderTree 这部分的这个 UI 组件的值是来自于 folderTreeService，而资源管理和函数管理里面的这个值是来自父组件的 state。这也是为什么在资源管理里面为什么拿 service 的值会是空数组

**Comment by mortalYoung** [comment]
如果要相关实现可以参考：https://github.com/mortalYoung/Taier/commit/bf22a667841732e6d3c8099df15890b2fc11d290 
大致的理解如下： molecule 中 export 出来的组件都是 UI 组件，主要负责渲染 不负责数据的存储。数据的存储可以选择放到 service 里面去也可以放到父组件的 state 中。
molecule 中默认布局是通过 `UI 组件+service+controller` 的方式去实现的，把所有数据都放到 service 中。我在 taier 里面没有吧 expandKeys 放到 service 里，而是放到父组件的 state 里面

**Comment by StrangeXin** [comment]
感谢，学到了！
