### ISSUE TITLE
bug: 出现多处渲染多个相同的tab，panel

### ISSUE THREAD

**Issue by jasonChen1234** [DTStack/molecule#842]
### Describe the bug

出现多处渲染多个相同的tab，panel

### Versions

"molecule": "1.3.0",
"react": "^17.0.0",
"umi": "^3.5.36",
"antd": "^4.23.6",

### Actually happening

![image](https://user-images.githubusercontent.com/90957501/217482709-7fd63a97-5d52-4b1e-a63a-651918ba11d4.png)

**Comment by jasonChen1234** [comment]
阅读了下源码发现有个 Provider ，可以先使用该 Provider 处理

![image](https://user-images.githubusercontent.com/90957501/217494020-39c79d9c-bac4-406f-87d1-4f18d060eaa2.png)

**Comment by wewoor** [comment]
不知道你的代码逻辑，尽可能的避免 molecule 实例被多次执行：
```
const moInstance = create({
    extensions: [],
});
```
