### ISSUE TITLE
<Workbench />组件类型问题导致项目启动报错

### ISSUE THREAD

**Issue by resetsix** [DTStack/molecule#859]
## 报错描述

尝试使用`yarn add @dtinsight/molecule`或`yarn create @dtinsight/`命令安装完依赖启动后都提示  < Workbench />   组件不是一个JSX元素类型导致启动报错。
---
代码静态时并没有报错提示，在项目启动编译时报错。

![图片](https://github.com/DTStack/molecule/assets/85431995/1164b4fb-1101-4c99-a1aa-b51d421f80ff)

![图片](https://github.com/DTStack/molecule/assets/85431995/4407a319-5d5d-444b-97a1-4b09ebbc350d)

## 使用版本
react 18.2.0
ts 4.4.2
yarn 1.22.19
node 16.18.0

**Comment by mortalYoung** [comment]
是用 molecule 的脚手架初始化的仓库么？看一下 `@types/react` 的版本是不是不是 18.x 的

**Comment by resetsix** [comment]
> 是用 molecule 的脚手架初始化的仓库么？看一下 `@types/react` 的版本是不是不是 18.x 的

是18.x。使用的`yarn create @dtinsight/`命令

![图片](https://github.com/DTStack/molecule/assets/85431995/b343046c-509b-49e8-8989-180ad2f3bf43)

**Comment by mortalYoung** [comment]
删除 node_modules 和 .lock 文件，重装一下依赖试试

**Comment by resetsix** [comment]
> 删除 node_modules 和 .lock 文件，重装一下依赖试试

重新安装依赖了也不行，项目我也重装过很多遍。我觉得可能是TS的问题，把`App.tsx`修改成`App.jsx`在启动的时候不经过编译就能启动成功。不知道是**TS版本过高**原因还是什么？我全局安装TS版本是最新的5.2.2；但项目中自带的是4.4。我不知道启动的时候编译的版本会选择哪个？我问gpt说是会选择项目中的版本。

![图片](https://github.com/DTStack/molecule/assets/85431995/05717bb5-8700-4f22-87d8-11f93b1e4330)

**Comment by mortalYoung** [comment]
![image](https://github.com/DTStack/molecule/assets/18719701/6747c23d-4124-4148-b6c3-579534f26be6)
我本地试了一下没有复现，但是我是用 pnpm 装的依赖

**Comment by mortalYoung** [comment]
> 我不知道启动的时候编译的版本会选择哪个

VSCode 做 typescript 的类型检查的时候，会用 VSCode 的版本，这个可以打开一个 .tsx 文件，然后看右下角 TypeScript JSX 边上的 `{}`，会显示当前版本。
![image](https://github.com/DTStack/molecule/assets/18719701/3fc109e0-ebcc-4139-9547-37365a502dca)

然后启动项目的时候，编译用的是项目里的版本。我看这个报错应该是类型不兼容导致的

**Comment by HaydenOrz** [comment]
可以在 package.json  中通过`resolutions `  字段，强制制定 react 相关类型包的版本试试，比如
```json
"resolutions": {
  "@types/react": "xxx",
  "@types/react-dom": "xxx",
},
```

**Comment by resetsix** [comment]
> ![image](https://user-images.githubusercontent.com/18719701/270222148-6747c23d-4124-4148-b6c3-579534f26be6.png) 我本地试了一下没有复现，但是我是用 pnpm 装的依赖

难受，我使用pnpm也不得行。

![图片](https://github.com/DTStack/molecule/assets/85431995/b4d9e7c0-76a7-4fe3-a43e-a65047212dfc)

这是我的本地代码：https://github.com/resetsix/ide

**Comment by resetsix** [comment]
> 可以在 package.json 中通过`resolutions ` 字段，强制指定 react 相关类型包的版本试试，比如
> 
> ```json
> "resolutions": {
>   "@types/react": "xxx",
>   "@types/react-dom": "xxx",
> },
> ```

好嘞 我试试。麻烦了大佬 感谢感谢
