### ISSUE TITLE
提示用户保存时，关闭 editor tab 标签页 tab 没有关闭成功

### ISSUE THREAD

**Issue by resetsix** [DTStack/molecule#875]
### Question

我想要实现的feature是：用户close editor tab 时要提示用户是否保存。（弹出一个对话Modal）

我模拟的情况是：当用户 close editor tab 时就提示对话框。（测试代码中没有去updateTab的状态，我想应该不影响吧）

> extensions集合的入口

![extensions](https://github.com/DTStack/molecule/assets/85431995/340d6e77-4964-40db-852b-c57954324051)

> Comfirm拓展具体代码

![comfirm](https://github.com/DTStack/molecule/assets/85431995/f11dffc5-e300-495f-871b-d4a1bee13bfe)

> 对话框

![modal](https://github.com/DTStack/molecule/assets/85431995/6a28df19-3724-40c2-8522-386f962f7ac6)

> UI

![图片](https://github.com/DTStack/molecule/assets/85431995/4c9e6be6-1908-47da-a8e8-63c2fa470d42)

我最开始怀疑是打开的和需要关闭的tabId和groupId不匹配，但后来检查都是一样的，我就伤脑筋了。

**Comment by mortalYoung** [comment]
不需要在 onOk 的时候调用 emit 的方法。直接调用 `molecule.editor.closeTab` 即可

**Comment by resetsix** [comment]
> 不需要在 onOk 的时候调用 emit 的方法。直接调用 `molecule.editor.closeTab` 即可

是这样吗？没生效呢。还是只关闭了 Modal 没关闭 tab

```
onOk={() => molecule.editor.closeTab(tabId, groupId)}
```

**Comment by mortalYoung** [comment]
是不是没有执行到 onOk 函数？直接离开的按钮看起来点击会调用 `modal.remove` 但是不会触发 onOk 吧？

**Comment by resetsix** [comment]
> 是不是没有执行到 onOk 函数？直接离开的按钮看起来点击会调用 `modal.remove` 但是不会触发 onOk 吧？

我也注意到了，抱歉，是我太粗心了。

我想再请教最后一个问题：我看molecule_demo这里正常情况是有运行按钮的，但是我本地没有，渲染的是Workbench。运行按钮是否是自行配置的呢？同时是否支持拓展其他的操作事件呢？

```
const App = () => moInstance.render(<Workbench />);
```
> 本地

![图片](https://github.com/DTStack/molecule/assets/85431995/24245c99-d3be-4aa6-b41b-7edc8daf406a)

> molecule_demo

![图片](https://github.com/DTStack/molecule/assets/85431995/7adeabd6-4485-40e0-87a5-a4652205c0d7)

**Comment by mortalYoung** [comment]
是自行配置的
```js
const EDITOR_ACTION_RUNNING: IEditorActionsProps = {
    id: EDITOR_ACTION_RUNNING_ID,
    name: 'Run',
    icon: 'play',
    place: 'outer',
    disabled: false,
    title: 'Running',
}

const builtInEditorInitialActions = molecule.builtin.getModule('builtInEditorInitialActions');
molecule.editor.setDefaultActions([ 
  {...EDITOR_ACTION_RUNNING }, 
  ...builtInEditorInitialActions?.value
]);
```


然后通过 `molecule.editor.onActionsClick` 来获取事件的交互，通过 `molecule.editor.updateActions` 来更新 loading 的状态
