### ISSUE TITLE
向molecule.editor.editorInstance中注册事件

### ISSUE THREAD

**Issue by YuanWangZai** [DTStack/molecule#880]
### Question
我想要在代码编辑器中添加打断点的功能，例如[Monaco Editor断点基础功能详解](https://blog.csdn.net/qq_34360984/article/details/134836178)。现在已经实现了这个初始化的函数，一开始尝试作为一个拓展来初始化，但是在没有打开任何tab的时候editorInstance是undefined。
目前我的解决方法是在open一个代码页面之后调用该函数初始化，但是在切换不同的editor Tab时候（有些editor Tab没有代码编辑器，是自己实现的renderPane），切换回来的时候断点功能会失效。
想请问有没有什么方法在没有打开Tab的时候注册一个editorInstance，或者在某些更合适的时机来调用初始化断点功能的函数，谢谢。

**Comment by mortalYoung** [comment]
目前看起来貌似没有特别好的时机可以获取到 editorInstance。大概现在只能通过 editor.onOpenTab 或者 editor.onSelectTab 然后加一个 setTimeout 来获取
不如添加一个新的事件，用于获取 editorInstance
