### ISSUE TITLE
请问如何更改默认的功能？

### ISSUE THREAD

**Issue by caoyang2002** [DTStack/molecule#899]
### Question

我想要创建文件，内置提供的按钮无法使用，我需要更改创建文件按钮的逻辑，我看了文档后仍然没有理解如何解决这个问题

<img width="293" alt="image" src="https://github.com/user-attachments/assets/c105279f-0b8a-40e7-a086-ab8674250da7">

**Comment by kiwiwong** [comment]
点击新建文件按钮会触发 folderTree 的 onCreate 事件，可以通过 extension 来自定义创建逻辑，可以参考我们demo里的实现：
https://github.com/DTStack/molecule/blob/69e4f3bc8b6f2028571d92e76ee49ba3eb88ba94/stories/extensions/test/index.tsx#L100
https://github.com/DTStack/molecule/blob/69e4f3bc8b6f2028571d92e76ee49ba3eb88ba94/stories/extensions/test/testPane.tsx#L451
