### ISSUE TITLE
2.0 什么时候会发新版本？

### ISSUE THREAD

**Issue by slobber** [DTStack/molecule#903]
感觉在 alpha6 之后已经 pr 了很多内容，什么时候会发布新版本？

**Comment by mortalYoung** [comment]
目前是在内部项目中做验证，如果验证顺利的话，期望是年内可以发 beta 版本。后续补充文档和单测内容，优化 API 的 JSDoc 等内容之后发布正式版

**Comment by slobber** [comment]
好的，谢谢
